repos:
    - repo: https://github.com/PyCQA/autoflake
      rev: v2.3.1
      hooks:
          - id: autoflake
            verbose: true

    - repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
          - id: absolufy-imports
            verbose: true
            args: ["--application-directories=.:src"]

    - repo: https://github.com/asottile/pyupgrade
      rev: v3.2.0
      hooks:
          - id: pyupgrade
            verbose: true
            args: [--py38-plus]

    - repo: https://github.com/timothycrosley/isort
      rev: 5.13.2
      hooks:
          - id: isort
            verbose: true

    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
          - id: black
            verbose: true

    - repo: local
      hooks:
      - id: pylint
        verbose: true
        name: pylint
        entry: pylint -rn -sn --rcfile=pyproject.toml
        language: system
        types: [python]

    - repo: local
      hooks:
      - id: mypy
        verbose: true
        name: mypy
        entry: mypy
        language: system
        types: [python]

