repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.11.2
      hooks:
        # Run the linter.
        - id: ruff
          args: [ --fix ]
        # Run the formatter.
        - id: ruff-format

    - repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
        - id: absolufy-imports
          verbose: true
          args: ["--application-directories=.:app"]

    - repo: local
      hooks:
        - id: mypy
          verbose: true
          name: mypy
          entry: mypy
          language: system
          types: [python]

