x-base: &base
  build: .
  working_dir: /code

services:
  draft_mtg:
    <<: *base
    volumes:
      - ./app:/code/app
    depends_on:
      - db
    command: uvicorn app.main:app --reload
    ports:
      - "8000:8000"

  pre-commit:
    <<: *base
    environment:
      - PRE_COMMIT_HOME=/hooks/pre-commit
    volumes:
      - .:/code
      - hooks:/hooks/pre-commit
    command: pre-commit run --all-files
    profiles:
      - test

  test:
    <<: *base
    volumes:
      - .:/code
    command: pytest
    profiles:
      - test

  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  hooks:
  postgres_data:
