services:
  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always
    ports:
      - 1337:80
    networks:
      - draft_mtg_network

  web:
    image: ghcr.io/filipkarpinski/draft-mtg:latest
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/code/app
    command: >
      sh -c "
        uv run alembic upgrade head &&
        uv run uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - draft_mtg_network


  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    networks:
      - draft_mtg_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  draft_mtg_network:
    name: draft_mtg_network

volumes:
  postgres_data:
