services:
  web:
    image: ghcr.io/filipkarpinski/draft-mtg:latest
    restart: always
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code
    command: >
      sh -c "
        sleep 2 &&
        cd app && alembic upgrade head &&
        cd .. && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
