services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - nginx

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always

  web:
    image: ghcr.io/filipkarpinski/draft-mtg:latest
    restart: always
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code
    command: >
      sh -c "
        sleep 2 &&
        cd app && alembic upgrade head &&
        cd .. && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
