"""empty message

Revision ID: 16755b2953fd
Revises: d03fd5738693
Create Date: 2025-03-19 16:38:28.149803

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16755b2953fd"
down_revision: Union[str, None] = "d03fd5738693"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(length=128), nullable=False))
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
