"""Add rounds table and update matches

Revision ID: 180d4582a349
Revises: 4989faef3c48
Create Date: 2025-05-30 16:16:13.084569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180d4582a349'
down_revision: Union[str, None] = '4989faef3c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_profile_picture_path'), table_name='players')
    op.drop_column('players', 'profile_picture_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('profile_picture_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_players_profile_picture_path'), 'players', ['profile_picture_path'], unique=False)
    # ### end Alembic commands ###
