"""add migration

Revision ID: 454ed962799a
Revises: eccc86aacfbe
Create Date: 2025-06-06 11:34:23.433526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454ed962799a'
down_revision: Union[str, None] = 'eccc86aacfbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drafts_name'), table_name='drafts')
    op.create_index(op.f('ix_drafts_name'), 'drafts', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drafts_name'), table_name='drafts')
    op.create_index(op.f('ix_drafts_name'), 'drafts', ['name'], unique=False)
    # ### end Alembic commands ###
