"""Add rounds table and update matches

Revision ID: 4989faef3c48
Revises: 70a997e017fb
Create Date: 2025-05-30 16:09:44.330251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4989faef3c48'
down_revision: Union[str, None] = '70a997e017fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_id'), 'rounds', ['id'], unique=False)
    op.alter_column('draft_players', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('matches', sa.Column('round_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('matches_draft_id_fkey'), 'matches', type_='foreignkey')
    op.create_foreign_key(None, 'matches', 'rounds', ['round_id'], ['id'])
    op.drop_column('matches', 'round')
    op.drop_column('matches', 'draft_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('draft_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('matches', sa.Column('round', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.create_foreign_key(op.f('matches_draft_id_fkey'), 'matches', 'drafts', ['draft_id'], ['id'])
    op.drop_column('matches', 'round_id')
    op.alter_column('draft_players', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_rounds_id'), table_name='rounds')
    op.drop_table('rounds')
    # ### end Alembic commands ###
