"""add migration

Revision ID: 51ca34677a40
Revises: 454ed962799a
Create Date: 2025-06-06 11:42:17.813921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ca34677a40'
down_revision: Union[str, None] = '454ed962799a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_players', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_draft_players_id'), 'draft_players', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_players_id'), table_name='draft_players')
    op.drop_column('draft_players', 'id')
    # ### end Alembic commands ###
