"""empty message

Revision ID: 6924f25e80a5
Revises: 783704b79d5c
Create Date: 2025-04-10 15:49:12.463766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6924f25e80a5'
down_revision: Union[str, None] = '783704b79d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'score',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'score',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
