"""create migration

Revision ID: 921e20dc6813
Revises: fca2f6b674fb
Create Date: 2025-06-06 13:37:20.979853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921e20dc6813'
down_revision: Union[str, None] = 'fca2f6b674fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_players_id'), table_name='draft_players')
    op.drop_column('draft_players', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_players', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_draft_players_id'), 'draft_players', ['id'], unique=False)
    # ### end Alembic commands ###
