"""empty message

Revision ID: a66802017847
Revises: 86d0f5b1e948
Create Date: 2025-04-11 05:48:01.414519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66802017847'
down_revision: Union[str, None] = '86d0f5b1e948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_players', sa.Column('points', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft_players', 'points')
    # ### end Alembic commands ###
