"""add migration

Revision ID: eccc86aacfbe
Revises: 180d4582a349
Create Date: 2025-06-06 11:24:04.827117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eccc86aacfbe'
down_revision: Union[str, None] = '180d4582a349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_players', sa.Column('deck_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft_players', 'deck_colors')
    # ### end Alembic commands ###
