"""empty message

Revision ID: f118f6cac19c
Revises: fa5fee7d0885
Create Date: 2025-03-20 15:53:14.153515

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f118f6cac19c"
down_revision: Union[str, None] = "fa5fee7d0885"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
